#!/bin/bash

# Change Default Audio Sink Volume by +/-5%
# Copyright (C) 2020, Jacob Still github.com/jcstill
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see https://www.gnu.org/licenses/

CURVOL="$(amixer -c 1 -M -D pulse get Master | tail -1 | awk '{print $5;}' | cut -c 2- | rev | cut -c 3- | rev )" # have to use "rev" since volume percent character length changes

if [ "$1" == "up" ]; then
	if [ "$CURVOL" -lt "100" ]; then
		pactl set-sink-volume @DEFAULT_SINK@ +5%
	fi
elif [ "$1" == "dn" ]; then
	if [ "$CURVOL" -gt "0" ]; then
		pactl set-sink-volume @DEFAULT_SINK@ -5%
	fi
fi
