#!/bin/bash

# Detailed information on an IP address or hostname in bash via https://ipinfo.io
# Copyright (C) 2020, Jacob Still github.com/jcstill
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see https://www.gnu.org/licenses/

if [ "$1" == "-h" ] || [ "$1" == "--help" ];then
	echo "Usage: ipinfo <DOMAIN>"
	exit 1
elif [ "$1" != "" ]; then
	if grep -P "(([1-9]\d{0,2})\.){3}(?2)" <<< "$1"; then
		curl -s https://ipinfo.io/"$1" | sed 's/\"//g'
	else
		ip=($(host "$1" | awk '/address/ { print $NF }'))
		curl -s https://ipinfo.io/${ip[0]} | sed 's/\"//g'
	fi
else
	curl -s https://ipinfo.io/ | sed 's/\"//g'
fi
echo
