#!/bin/bash

# Disable Mouse/Keyboard Wakeups from suspend
# Copyright (C) 2020, Jacob Still github.com/jcstill
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see https://www.gnu.org/licenses/

ENABLED="$(grep XHC</proc/acpi/wakeup|cut -f3|cut -d " " -f1)"
if [ "$ENABLED" == "*enabled"  ]; then
	sudo su -c "echo XHC > /proc/acpi/wakeup"
		echo Disabling HID wake from sleep.
else
	echo HID wake from sleep already disabled.
fi
